title: RIDHI SHARMA
#logo: /assets/img/headshot_circle.png
description: Passionate programmer | Front-end focused | Open to collaboration | Let's build the future together! 🌟
show_downloads: true
theme: jekyll-theme-cayman
